import { expect, describe, it } from 'vitest'
import { convert } from "../src/kata"

describe("number less than 20", () => {
    it('translate 0 to zéro', () => {
        expect(convert(0)).toEqual('zéro')
    })
    it('translate 1 to un', () => {
        expect(convert(1)).toEqual('un')
    })
    it('translate 2 to deux', () => {
        expect(convert(2)).toEqual('deux')
    })
    it('translate 3 to trois', () => {expect(convert(3)).toEqual('trois')})
    it('translate 4 to quatre', () => {expect(convert(4)).toEqual('quatre')
    })
    it('translate 5 to cinq', () => {expect(convert(5)).toEqual('cinq')
    })
    it('translate 6 to six', () => {expect(convert(6)).toEqual('six')
    })
    it('translate 7 to sept', () => {expect(convert(7)).toEqual('sept')
    })
    it('translate 8 to huit', () => {expect(convert(8)).toEqual('huit')
    })
    it('translate 9 to neuf', () => {expect(convert(9)).toEqual('neuf')
    })
    it('translate 10 to dix', () => {expect(convert(10)).toEqual('dix')
    })
    it('translate 11 to onze', () => {expect(convert(11)).toEqual('onze')
    })
    it('translate 12 to douze', () => {expect(convert(12)).toEqual('douze')
    })
    it('translate 13 to treize', () => {expect(convert(13)).toEqual('treize')
    })
    it('translate 14 to quatorze', () => {expect(convert(14)).toEqual('quatorze')
    })
    it('translate 15 to quinze', () => {expect(convert(15)).toEqual('quinze')
    })
    it('translate 16 to seize', () => {expect(convert(16)).toEqual('seize')
    })
    it('translate 17 to dix-sept', () => {expect(convert(17)).toEqual('dix-sept')
    })
    it('translate 18 to dix-huit', () => {expect(convert(18)).toEqual('dix-huit')
    })
    it('translate 19 to dix-neuf', () => {
        expect(convert(19)).toEqual('dix-neuf')
    })
})

describe("tens", () => {
    it('translate 10 to dix', () => {expect(convert(10)).toEqual('dix')
    })
    it('translate 20 to vingt', () => {expect(convert(20)).toEqual('vingt')
    })
    it('translate 30 to trente', () => {expect(convert(30)).toEqual('trente')
    })
    it('translate 40 to quarante', () => {expect(convert(40)).toEqual('quarante')
    })
    it('translate 50 to cinquante', () => {expect(convert(50)).toEqual('cinquante')
    })
    it('translate 60 to soixante', () => {expect(convert(60)).toEqual('soixante')
    })
    it('translate 70 to soixante-dix', () => {expect(convert(70)).toEqual('soixante-dix')
    })
    it('translate 80 to quatre-vingts', () => {expect(convert(80)).toEqual('quatre-vingts')
    })
    it('translate 90 to quatre-vingt-dix', () => {expect(convert(90)).toEqual('quatre-vingt-dix')
    })
})

describe("number below 70", () => {
    it('translate 22 to vingt-deux', () => {expect(convert(22)).toEqual('vingt-deux')
    })
    it('translate 33 to trente-trois', () => {expect(convert(33)).toEqual('trente-trois')
    })
    it('translate 54 to cinquante-quatre', () => {expect(convert(54)).toEqual('cinquante-quatre')
    })
    it('translate 69 to soixante-neuf', () => {expect(convert(69)).toEqual('soixante-neuf')
    })
})

describe("quatre-vingts takes an S when not followed by anything", () => {
    it('translate 80 to quatre-vingts, with an S', () => {expect(convert(80)).toEqual('quatre-vingts')
    })
    it('translate 82 to quatre-vingt-deux, without  S', () => {expect(convert(82)).toEqual('quatre-vingt-deux')
    })
    it('translate 84 to quatre-vingt-quatre, without  S', () => {expect(convert(84)).toEqual('quatre-vingt-quatre')
    })
    it('translate 89 to quatre-vingt-neuf, without  S', () => {expect(convert(89)).toEqual('quatre-vingt-neuf')
    })
})

describe("70 to 80 numbers and 90 to 100 numbers do not use the same pattern as others", () => { 
    it('translate 72 to soixante-douze', () => {expect(convert(72)).toEqual('soixante-douze')
    })
    it('translate 73 to soixante-treize', () => {expect(convert(73)).toEqual('soixante-treize')
    })
    it('translate 79 to soixante-dix-neuf', () => {expect(convert(79)).toEqual('soixante-dix-neuf')
    })
    it('translate 92 to quatre-vingt-douze', () => {expect(convert(92)).toEqual('quatre-vingt-douze')
    })
    it('translate 96 to quatre-vingt-seize', () => {expect(convert(96)).toEqual('quatre-vingt-seize')
    })
    it('translate 99 to quatre-vingt-dix-neuf', () => {expect(convert(99)).toEqual('quatre-vingt-dix-neuf')
    })
})

  describe("hundreds: like vingts, cents can be plural if it is not followed by something else", () => {
    it('translate 100 to cent', () => {expect(convert(100)).toEqual('cent')
    })
    it('translate 200 to deux-cents, with an S', () => {expect(convert(200)).toEqual('deux-cents')
    })
    it('translate 600 to six-cents, with an S', () => {expect(convert(600)).toEqual('six-cents')
    })
    it('translate 305 to trois-cent-cinq, without S at cent', () => {expect(convert(305)).toEqual('trois-cent-cinq')
    })
    it('translate 480 to quatre-cent-quatre-vingts, without S at cent, but with an S at vingts', () => {expect(convert(480)).toEqual('quatre-cent-quatre-vingts')
    })
    it('translate 999 to neuf-cent-quatre-vingt-dix-neuf, without S at cent', () => {expect(convert(999)).toEqual('neuf-cent-quatre-vingt-dix-neuf')
    })
  })

  describe("some numbers ending with 1 are joined with dashes, others with dashes and 'et'", () => {
    //traditional french use "vingt et un" with spaces, but since 1990 reform the rule is "vingt-et-un" with dashes.
    //and it is easier to do!
    it('translate 21 to vingt-et-un', () => {expect(convert(21)).toEqual('vingt-et-un')
    })
    it('translate 31 to trente-et-un', () => {expect(convert(31)).toEqual('trente-et-un')
    })
    it('translate 41 to quarante-et-un', () => {expect(convert(41)).toEqual('quarante-et-un')
    })
    it('translate 51 to cinquante-et-un', () => {expect(convert(51)).toEqual('cinquante-et-un')
    })
    it('translate 61 to soixante-et-un', () => {expect(convert(61)).toEqual('soixante-et-un')
    })
    it('translate 71 to soixante-et-onze', () => {expect(convert(71)).toEqual('soixante-et-onze')
    })
    it('translate 81 to quatre-vingt-un, without "et"', () => {expect(convert(81)).toEqual('quatre-vingt-un')
    })
    it('translate 91 to quatre-vingt-onze, without "et"', () => {expect(convert(91)).toEqual('quatre-vingt-onze')
    })
    it('translate 101 to cent-un, without "et"', () => {expect(convert(101)).toEqual('cent-un')
    })
    it('translate 111 to cent-onze, without "et"', () => {expect(convert(111)).toEqual('cent-onze')
    })
    it('translate 151 to cent-cinquante-et-un, with "et"', () => {expect(convert(151)).toEqual('cent-cinquante-et-un')
    })
    it('translate 991 to neuf-cent-quatre-vingt-onze, without "et"', () => {expect(convert(991)).toEqual('neuf-cent-quatre-vingt-onze')
    })
})

describe("from thousand to millions. Like vingt and cent, mille can be plural", () => {
    it('translate 1000 to mille', () => {expect(convert(1000)).toEqual('mille')
    })
    it('translate 1045 to mille-quarante-cinq', () => {expect(convert(1045)).toEqual('mille-quarante-cinq')
    })
    it('translate 1145 to mille-cent-quarante-cinq', () => {expect(convert(1145)).toEqual('mille-cent-quarante-cinq')
    })
    it('translate 2000 to deux-milles, with an S', () => {expect(convert(2000)).toEqual('deux-milles')
    })
    it('translate 2005 to deux-mille-cinq, without an S', () => {expect(convert(2005)).toEqual('deux-mille-cinq')
    })
    it('translate 9999 to neuf-mille-neuf-cent-quatre-vingt-dix-neuf', () => {expect(convert(9999)).toEqual('neuf-mille-neuf-cent-quatre-vingt-dix-neuf')
    })
    it('translate 10000 to dix-milles, with an S', () => {expect(convert(10000)).toEqual('dix-milles')
    })
    it('translate 20000 to vingt-milles, with an S', () => {expect(convert(20000)).toEqual('vingt-milles')
    })
    it('translate 80000 to quatre-vingt-milles, with an S at mille but not vingt', () => {expect(convert(80000)).toEqual('quatre-vingt-milles')
    })
    it('translate 100000 to cent-milles, with an S', () => {expect(convert(100000)).toEqual('cent-milles')
    })
    it('translate 153622 to cent-cinquante-trois-mille-six-cent-vingt-deux', () => {expect(convert(153622)).toEqual('cent-cinquante-trois-mille-six-cent-vingt-deux')
    })
    it('translate 153622 to cent-cinquante-trois-mille-six-cent-vingt-deux', () => {expect(convert(153622)).toEqual('cent-cinquante-trois-mille-six-cent-vingt-deux')
    })
    it('translate 999999 to neuf-cent-quatre-vingt-dix-neuf-mille-neuf-cent-quatre-vingt-dix-neuf', () => {expect(convert(999999)).toEqual('neuf-cent-quatre-vingt-dix-neuf-mille-neuf-cent-quatre-vingt-dix-neuf')
    })
 })

  describe("specific rule for Et when number ends with 1 are still working for thousands", () => {   
    it('translate 2171 to deux-mille-cent-soixante-et-onze, with et', () => {
        expect(convert(2171)).toEqual('deux-mille-cent-soixante-et-onze')
    })
    it('translate 2191 to deux-mille-cent-quatre-vingt-onze, without et', () => {
        expect(convert(2191)).toEqual('deux-mille-cent-quatre-vingt-onze')
    })

    it('translate 51051 to cinquante-et-un-mille-cinquante-et-un, with et in both thousand and units', () => {
        expect(convert(51051)).toEqual('cinquante-et-un-mille-cinquante-et-un')
    })
    it('translate 81081 to quatre-vingt-un-mille-quatre-vingt-un, without et', () => {
        expect(convert(81081)).toEqual('quatre-vingt-un-mille-quatre-vingt-un')
    })
    it('translate 51081 to cinquante-et-un-mille-quatre-vingt-un, with et in thousand but not in units', () => {
        expect(convert(51081)).toEqual('cinquante-et-un-mille-quatre-vingt-un')
    })
    it('translate 81051 to quatre-vingt-un-mille-cinquante-et-un, with et in units but not in thousands', () => {
        expect(convert(81051)).toEqual('quatre-vingt-un-mille-cinquante-et-un')
    })
 })